// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"go-image-process/internal/conf"
	"go-image-process/internal/server"
	"go-image-process/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	imageInterface, cleanup := service.NewImage(bootstrap)
	httpServer := server.NewHTTPServer(bootstrap, imageInterface)
	app := newApp(httpServer)
	return app, func() {
		cleanup()
	}, nil
}
